// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	UserTable1 string
	UserTable2 string
	UserTable3 string
}{
	UserTable1: "user_table1",
	UserTable2: "user_table2",
	UserTable3: "user_table3",
}
