// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("UserTable1s", testUserTable1sUpsert)

	t.Run("UserTable2s", testUserTable2sUpsert)

	t.Run("UserTable3s", testUserTable3sUpsert)
}
